// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:factory_erp_lite/modules/expense/model/local/expense_hive_model.dart';
import 'package:factory_erp_lite/modules/factory_status/model/local/factory_status_hive_model.dart';
import 'package:factory_erp_lite/modules/labor_management/model/local/labor_hive_model.dart';
import 'package:factory_erp_lite/modules/person_management/model/local/person_hive_model.dart';
import 'package:factory_erp_lite/modules/recurring_expenses/model/local/recurring_expense_hive_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(ExpenseHiveModelAdapter());
    registerAdapter(FactoryStatusHiveModelAdapter());
    registerAdapter(LaborHiveModelAdapter());
    registerAdapter(PersonHiveModelAdapter());
    registerAdapter(RecurringExpenseHiveModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(ExpenseHiveModelAdapter());
    registerAdapter(FactoryStatusHiveModelAdapter());
    registerAdapter(LaborHiveModelAdapter());
    registerAdapter(PersonHiveModelAdapter());
    registerAdapter(RecurringExpenseHiveModelAdapter());
  }
}
